application: zipcode-3plus2
version: 1

runtime: python
api_version: 1

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /zipcode/media
  static_dir: apps/zipcode/media

#- url: /(.*\.(ico|gif|png|jpg))
#  static_files: apps/zipcode/media/\1
#  upload: apps/zipcode/media/(.*\.(gif|png|jpg))

- url: /.*
  script: main.py
#  login: required
