application: chang-mao
version: 1

runtime: python
api_version: 1

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

## Static: Gaebar
#- url: /gaebar/static
#  static_dir: gaebar/static

#- url: /authuser/media
#  static_dir: apps/authuser/media

#- url: /management/media
#  static_dir: apps/management/media

#- url: /requestticket/media
#  static_dir: apps/requestticket/media

#- url: /(.*\.(ico|gif|png|jpg))
#  static_files: apps/originpatent/media/\1
#  upload: apps/originpatent/media/(.*\.(gif|png|jpg))

#- url: /Upgrade/.*
#  script: main.py
#  login: admin

#- url: /Danger/.*
#  script: main.py
#  login: admin

#- url: /step1.*
#  script: step1.py
#  login: required

#- url: /step2.*
#  script: step2.py
#  login: required

#- url: /requestticket/queue/
#  script: main.py
#  login: admin

#- url: /requestticket/cron/
#  script: main.py
#  login: admin

#- url: /.*
#  script: main.py
#  login: required
